/* VETS Explorer — isolated Highcharts card rendering and exhibit encoding.
 * window.vetsRenderCards draws the composer's cards off screen (vets.js calls
 * it directly; there is no Shiny message for it). vets-write-exhibit consumes only R's
 * validated SVG pages and returns PDF/PNG base64 bound to writer + capture IDs.
 * PNG rasterises at the resolution R asked for (png_resolution, #283): dpi/72
 * pixels per page point, refusing a page beyond this browser's canvas limit
 * rather than drawing it smaller.
 * Browser dispatch uses a producer map checked against export_formats.R by tests.
 * SVG/HTML writers live in R. The client keeps transient job/cancellation state,
 * no workspace model. Temporary charts, SVGs and blob URLs are released.
 * PDF: unchanged vendored jsPDF 2.0.0 (Highcharts build) + svg2pdf 1.3.1, with
 * DejaVu Sans 2.37 embedded for Unicode; unsupported glyphs fail explicitly.
 * Download URLs are generated by R for each job, never constructed from titles.
 * See docs/exhibit-writers.md and www/vendor/ for licences/renderer limits.
 */
(function () {
  'use strict';

  var STAGE_ID = 'vets-export-stage';
  var SVG_NS = 'http://www.w3.org/2000/svg';

  function now() { return (window.performance && performance.now) ? performance.now() : Date.now(); }

  function stage() {
    var s = document.getElementById(STAGE_ID);
    if (!s) {
      s = document.createElement('div');
      s.id = STAGE_ID;
      s.setAttribute('aria-hidden', 'true');
      // Off-screen but laid out, so Highcharts measures real text widths.
      s.style.cssText = 'position:absolute;left:-20000px;top:0;width:0;height:0;overflow:visible;';
      document.body.appendChild(s);
    }
    return s;
  }

  function clearStage() {
    var s = document.getElementById(STAGE_ID);
    if (s) s.parentNode.removeChild(s);
  }

  function highcharts() {
    if (!window.Highcharts) throw new Error('Highcharts is not loaded');
    return window.Highcharts;
  }

  /* ---- 1. cards ----------------------------------------------------------- */

  // Custom-message JSON cannot transport htmlwidgets functions, and this stage
  // evaluates no serialized text: the period-axis callbacks and the render
  // geometry are bound from vets-chart-axis.js, the same functions the screen
  // widget names, so exported charts draw the ticks and labels the screen draws.
  function axisModule() {
    if (!window.vetsChartAxis) throw new Error('vets-chart-axis.js is not loaded');
    return window.vetsChartAxis;
  }
  function bindExportCallbacks(options) {
    var axis = axisModule();
    // The R options name the same functions; replace the names with them. Live
    // print handlers are not part of a static chart.
    options.chart.events = {render: axis.render};
    var axes = Array.isArray(options.xAxis) ? options.xAxis : [options.xAxis];
    axes.forEach(function (a) {
      if (!a || !a.vetsPeriodCentered) return;
      a.tickPositioner = axis.periodTicks;
      a.labels = highcharts().merge({}, a.labels, {formatter: axis.periodLabel});
    });
  }

  // One card at slot size: a fresh chart in the stage, its export SVG, then
  // the chart is destroyed. getSVG() draws a sandbox copy with forExport, so
  // the SVG is self-contained (no CSS classes needed to render it).
  function renderCardSvg(slot) {
    var div = document.createElement('div');
    div.style.width = slot.width + 'px';
    div.style.height = slot.height + 'px';
    stage().appendChild(div);
    var chart = null;
    try {
      // Isolate Highcharts' mutable options; dimensions are part of the hook,
      // even if the caller's option list carries different export defaults.
      var options = highcharts().merge({}, slot.options, {
        chart: { width: slot.width, height: slot.height, animation: false },
        exporting: { sourceWidth: slot.width, sourceHeight: slot.height }
      });
      // The R snapshot carries punctuation. Bind a fixed formatter to this
      // temporary chart so unrelated global language settings cannot change it.
      // No executable strings are accepted from a configuration or evaluated.
      if (options.lang) {
        options.chart.numberFormatter = function (number, decimals) {
          return highcharts().numberFormat(number, decimals, options.lang.decimalPoint, options.lang.thousandsSep);
        };
      }
      bindExportCallbacks(options);
      chart = highcharts().stockChart(div, options);
      return chart.getSVG();
    } finally {
      // Construction can register a chart and then throw (for example, an
      // invalid axis reference). The return value was never assigned then.
      if (!chart && div.hasAttribute('data-highcharts-chart')) {
        chart = highcharts().charts[Number(div.getAttribute('data-highcharts-chart'))];
      }
      if (chart) { try { chart.destroy(); } catch (x) { /* noop */ } }
      if (div.parentNode) div.parentNode.removeChild(div);
    }
  }

  // The composer (vets.js) consumes the synchronous return; nothing is sent
  // to R from here. Every off-screen card render goes through this one hook.
  window.vetsRenderCards = function (request) {
    var t0 = now(), result;
    try {
      if (!request || !Array.isArray(request.cards)) throw new Error('cards must be an array');
      var cards = request.cards.map(function (slot) {
        if (!Number.isFinite(slot.width) || !Number.isFinite(slot.height) ||
            slot.width <= 0 || slot.height <= 0) throw new Error('invalid card dimensions');
        return { card_id: slot.card_id, width: slot.width, height: slot.height, svg: renderCardSvg(slot) };
      });
      result = { job: request.job, cards: cards, timing: { render_ms: Math.round(now() - t0) } };
    } catch (e) {
      result = { job: request && request.job, error: String(e.message || e) };
    } finally {
      clearStage();
    }
    return result;
  };

  function blobToBase64(blob) {
    return new Promise(function (resolve, reject) {
      var r = new FileReader();
      r.onload = function () { resolve(String(r.result).split(',')[1]); };
      r.onerror = function () { reject(new Error('could not read the PDF blob')); };
      r.readAsDataURL(blob);
    });
  }

  /* ---- 2. rasterising: the canvas limit (#283) ---------------------------
   * A page is rasterised into ONE canvas, so its pixel size has to fit what
   * this browser will allocate. Blink stops at 65535 px a side, Gecko at
   * 32767 and WebKit lower still, and each also caps the total area.
   * The SIDE limit is PROBED rather than read from a table of browser
   * constants: a candidate-wide, one-pixel-tall canvas costs a few kilobytes,
   * so the answer is this browser's own, measured once per session.
   * The AREA stays a documented budget, because measuring it would mean
   * allocating the very gigabyte we are trying not to allocate. 64 Mpx is
   * 256 MB of canvas pixels before the base64 PNG, which must still cross the
   * websocket inside validate_exhibit_export's 128 MiB payload bound. It
   * admits every shipped page at 600 dpi - Letter 5100 x 6600 = 33.7 Mpx,
   * Slide 16:9 8000 x 4500 = 36 Mpx - and refuses the large Custom pages
   * (up to 100 in a side) that would exhaust the tab. It is the bound this
   * writer has always applied, so no page that rasterises today stops doing so.
   * A page over either limit fails the job: R names the page, its pixel size
   * and the resolution, and the resolution is never lowered to make it fit.
   */
  var CANVAS_AREA_LIMIT = 64000000;
  var CANVAS_SIDE_CANDIDATES = [65535, 32767, 16384, 8192, 4096];
  var canvasSide = 0;
  function canvasHoldsSide(side) {
    var c = null;
    try {
      c = document.createElement('canvas');
      c.width = side; c.height = 1;
      if (c.width !== side) return false;
      var ctx = c.getContext('2d');
      if (!ctx) return false;
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(side - 1, 0, 1, 1);
      return ctx.getImageData(side - 1, 0, 1, 1).data[3] === 255;
    } catch (e) {
      return false;
    } finally {
      if (c) { c.width = 1; c.height = 1; }
    }
  }
  function canvasSideLimit() {
    if (canvasSide) return canvasSide;
    for (var i = 0; i < CANVAS_SIDE_CANDIDATES.length; i++) {
      if (canvasHoldsSide(CANVAS_SIDE_CANDIDATES[i])) { canvasSide = CANVAS_SIDE_CANDIDATES[i]; return canvasSide; }
    }
    canvasSide = CANVAS_SIDE_CANDIDATES[CANVAS_SIDE_CANDIDATES.length - 1];
    return canvasSide;
  }
  // Read-only, for an evidence driver to record what this browser reported;
  // nothing in the app reads it and no behaviour depends on it.
  window.__vetsCanvasLimit = function () { return {side: canvasSideLimit(), area: CANVAS_AREA_LIMIT}; };

  // R owns the wording; this carries the facts only R cannot know: which page
  // refused, and the resolution it was asked for (a capture PDF rasterises at
  // its own 288 dpi, ADR 0043).
  function pageTooLarge(px, py, dpi, page) {
    var error = new Error('The page is too large for an image capture (' + px + ' x ' + py +
      ' px at ' + dpi + ' dpi). Use a lower resolution, SVG or HTML.');
    error.vetsCode = 'png_too_large';
    error.vetsPage = page;
    error.vetsResolution = dpi;
    return error;
  }

  // A page SVG rasterised through <img> + canvas (what Highcharts' offline
  // PNG export does in Chrome): a same-origin blob URL, so the canvas is not
  // tainted and toDataURL works. `dpi` is the resolution R asked for; the
  // scale is dpi/72 because a page point is 1/72 in, computed here so the
  // floating-point pixels-per-point never crosses the wire.
  function svgToPngBase64(svgText, w, h, dpi, signal, page) {
    var scale = dpi / 72, px = Math.round(w * scale), py = Math.round(h * scale);
    var side = canvasSideLimit();
    if (px > side || py > side || px * py > CANVAS_AREA_LIMIT)
      return Promise.reject(pageTooLarge(px, py, dpi, page || 1));
    return new Promise(function (resolve, reject) {
      var url = URL.createObjectURL(new Blob([svgText], { type: 'image/svg+xml;charset=utf-8' }));
      var img = new Image();
      var timeout = setTimeout(function () { fail(new Error('Timed out drawing a PNG page')); },30000);
      function cleanup() {
        clearTimeout(timeout);
        if (signal) signal.removeEventListener('abort',cancel);
        img.onload=null;img.onerror=null;
        URL.revokeObjectURL(url);
      }
      function fail(error) {cleanup();reject(error);}
      function cancel() {fail(new Error('Export cancelled'));}
      if (signal) {
        signal.addEventListener('abort',cancel,{once:true});
        if (signal.aborted) {cancel();return;}
      }
      img.onload = function () {
        try {
          var c = document.createElement('canvas');
          c.width = px;
          c.height = py;
          var ctx = c.getContext('2d');
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(0, 0, c.width, c.height);
          ctx.drawImage(img, 0, 0, c.width, c.height);
          resolve(c.toDataURL('image/png').split(',')[1]);
        } catch (e) { reject(e); } finally { cleanup(); }
      };
      img.onerror = function () { fail(new Error('The browser could not draw a page SVG as an image')); };
      img.src = url;
    });
  }

  function pdfConstructor() {
    var J = window.jsPDF;
    if (typeof J === 'function') return J;
    if (J && typeof J.jsPDF === 'function') return J.jsPDF;
    throw new Error('jsPDF is not loaded (www/vendor/highcharts-9.3.1-lib/jspdf.js)');
  }

  // The three workarounds Highcharts 9.3.1's own svgToPdf applies before
  // handing an SVG to svg2pdf 1.3.1 (OfflineExporting.js): hidden elements
  // would be drawn, duplicate zero-offset gradient stops upset Acrobat, and
  // zero-width-space tspans break text placement. Plus one of ours: svg2pdf
  // 1.3.1 draws the text of a <title> child (the hover tooltip Highcharts
  // adds to a truncated label) as if it were visible, so those go too.
  function sanitizeForPdf(el) {
    // Highcharts emits placeholder paths without drawing commands. svg2pdf's
    // path parser dereferences a missing d attribute; empty paths draw nothing.
    el.querySelectorAll('path').forEach(function (path) {
      if (!(path.getAttribute('d') || '').trim()) path.remove();
    });
    [].forEach.call(el.querySelectorAll('*[visibility="hidden"]'), function (n) { n.parentNode.removeChild(n); });
    [].forEach.call(el.querySelectorAll('title'), function (n) { n.parentNode.removeChild(n); });
    var gradients = el.querySelectorAll('linearGradient');
    for (var gi = 0; gi < gradients.length; gi++) {
      var stops = gradients[gi].querySelectorAll('stop');
      var i = 0;
      while (i < stops.length && stops[i].getAttribute('offset') === '0' &&
             stops[i + 1] && stops[i + 1].getAttribute('offset') === '0') {
        stops[i].parentNode.removeChild(stops[i]);
        i++;
      }
    }
    [].forEach.call(el.querySelectorAll('tspan'), function (t) {
      if (t.textContent === '\u200b') { t.textContent = ' '; t.setAttribute('dx', -5); }
    });
  }

  /* ---- 4. the job --------------------------------------------------------- */

  function versions() {
    var v = { highcharts: window.Highcharts ? window.Highcharts.version : null,
              jspdf: null, svg2pdf: typeof window.svg2pdf === 'function' ? 'loaded' : null,
              userAgent: navigator.userAgent };
    try { var C = pdfConstructor(); v.jspdf = C.version || (C.API && C.API.version) || 'loaded'; } catch (x) { /* noop */ }
    return v;
  }

  function reply(m) {
    var summary = {};
    for (var k in m) if (k !== 'pages') summary[k] = m[k];
    window.__vetsExportLast = summary;
    if (window.vetsEvent) window.vetsEvent('vets_export_pages', m);
  }

  var activeWriter = null, latestJob = null, pdfFonts = null;
  var fontFiles = [
    {file:'DejaVuSans.ttf', style:'normal', weight:'normal', slant:'normal'},
    {file:'DejaVuSans-Bold.ttf', style:'bold', weight:'bold', slant:'normal'},
    {file:'DejaVuSans-Oblique.ttf', style:'italic', weight:'normal', slant:'italic'},
    {file:'DejaVuSans-BoldOblique.ttf', style:'bolditalic', weight:'bold', slant:'italic'}
  ];
  function loadPdfFonts() {
    if (!pdfFonts) pdfFonts = Promise.all(fontFiles.map(async function (font) {
      var response = await fetch('vendor/dejavu-sans/' + font.file);
      if (!response.ok) throw Error('The local PDF font could not be loaded');
      var buffer = await response.arrayBuffer();
      var face = new FontFace('VetsPDF', buffer, {weight:font.weight,style:font.slant});
      await face.load(); document.fonts.add(face);
      return {font:font, base64:await blobToBase64(new Blob([buffer]))};
    })).catch(function (error) { pdfFonts = null; throw error; });
    return pdfFonts;
  }
  function checkWriter(job) { if (job.cancelled) throw Error('Export cancelled'); }
  function yieldWriter() { return new Promise(function (resolve) {setTimeout(resolve,0);}); }

  var PDF_RASTER_DPI = 288;
  async function pagesToPdfBlob(request, job) {
    // Capture PDFs embed the same browser-rasterized page at 288 dpi. This
    // preserves Figtree and CSS text appearance without PDF font substitution.
    // SVG/HTML retain their vector charts and text.
    if (request.live) {
      var CapturedPDF=pdfConstructor(),first=request.page_sizes[0];
      var captured=new CapturedPDF(first.height>first.width?'p':'l','pt',[first.width,first.height]);
      if(request.metadata)captured.setProperties({subject:request.metadata});
      for(var n=0;n<request.pages.length;n++) {
        checkWriter(job);var pageSize=request.page_sizes[n];
        var png=await svgToPngBase64(request.pages[n],pageSize.width,pageSize.height,PDF_RASTER_DPI,job.controller && job.controller.signal,n+1);
        checkWriter(job);
        if(n)captured.addPage([pageSize.width,pageSize.height],pageSize.height>pageSize.width?'p':'l');
        captured.addImage('data:image/png;base64,'+png,'PNG',0,0,pageSize.width,pageSize.height,undefined,'FAST');
      }
      return captured.output('blob');
    }
    var fonts = await loadPdfFonts(); checkWriter(job);
    var W = request.page.width, H = request.page.height, orientation = H > W ? 'p' : 'l';
    var Ctor = pdfConstructor();
    if (typeof window.svg2pdf !== 'function') throw Error('The local SVG-to-PDF converter is unavailable');
    var pdf = new Ctor(orientation, 'pt', [W,H]);
    if (request.metadata) pdf.setProperties({subject: request.metadata});
    fonts.forEach(function (entry) {
      pdf.addFileToVFS(entry.font.file,entry.base64);
      pdf.addFont(entry.font.file,'VetsPDF',entry.font.style);
    });
    for (var i=0;i<request.pages.length;i++) {
      await yieldWriter();checkWriter(job);
      var size = request.page_sizes ? request.page_sizes[i] : request.page;
      W=size.width; H=size.height; orientation=H>W ? "p" : "l";
      if (i) pdf.addPage([W,H],orientation);
      var doc = new DOMParser().parseFromString(request.pages[i],'image/svg+xml');
      if (doc.querySelector('parsererror')) throw Error('Invalid captured SVG page');
      var el = document.importNode(doc.documentElement,true);
      stage().appendChild(el);
      try {
        sanitizeForPdf(el);
        // Apply the embedded substitute consistently through nested SVG styles.
        [el].concat(Array.from(el.querySelectorAll('*'))).forEach(function (node) {
          if (node.hasAttribute('font-family')) node.setAttribute('font-family','VetsPDF');
          if (node.style && node.style.fontFamily) node.style.fontFamily='VetsPDF';
        });
        el.querySelectorAll('text').forEach(function (text) {
          var style = getComputedStyle(text);
          var weight = Number(style.fontWeight)>=600 || style.fontWeight==='bold' ? 'bold' : '';
          if (style.fontStyle==='italic' || style.fontStyle==='oblique') weight+='italic';
          weight = weight || 'normal';
          pdf.setFont('VetsPDF',weight);
          var font = pdf.internal.getFont().metadata;
          Array.from(text.textContent).forEach(function (glyph) {
            var code = glyph.codePointAt(0);
            // This converter has no general shaping engine. Never pretend a
            // missing glyph, combining sequence or RTL run is a faithful PDF.
            if (!/\s/.test(glyph) && (code>65535 || !font.characterToGlyph(code) ||
                /[\u0300-\u036f\u0590-\u08ff\u200c-\u200f\u202a-\u202e\u2066-\u2069]/.test(glyph))) {
              throw Error('PDF font/shaping does not support U+'+code.toString(16).toUpperCase());
            }
          });
          // Keep measured annotations inside their reserved region when the
          // embedded font's advances differ from the installed screen font.
          var width = Number(text.dataset.textWidth);
          if (width>0 && text.children.length) {
            var advance = Math.max.apply(null,Array.from(text.children).map(function (span) {return span.getComputedTextLength();}));
            if (advance>width) {
              var x = Number(text.children[0].getAttribute('x'));
              text.setAttribute('transform','translate('+x+' 0) scale('+(width/advance)+' 1) translate('+(-x)+' 0)');
            }
          }
        });
        window.svg2pdf(el,pdf,{xOffset:0,yOffset:0,scale:1,removeInvalid:false});
      } finally { el.remove(); }
    }
    checkWriter(job);
    // This Highcharts jsPDF build writes the encoding name into CIDSystemInfo
    // Ordering. The collection is Adobe-Identity, while Encoding is Identity-H.
    // Correct only that exact structural line; equal byte length keeps every
    // xref offset valid and leaves the vendored library and font streams intact.
    var binary = pdf.output();
    binary = binary.replace(/\/Registry \(Adobe\)\n\/Ordering \(Identity-H\)/g,
      '/Registry (Adobe)\n/Ordering (Identity)  ');
    var bytes = new Uint8Array(binary.length);
    for (var j=0;j<binary.length;j++) bytes[j]=binary.charCodeAt(j);
    return new Blob([bytes],{type:'application/pdf'});
  }

  // Producer names are cross-checked against export_formats.R in test_ui_events.R.
  // No prototype keys can be mistaken for a supported format.
  var exhibitProducers=Object.create(null);
  exhibitProducers.pdf=async function(request,job) {
    return [await blobToBase64(await pagesToPdfBlob(request,job))];
  };
  exhibitProducers.png=async function(request,job) {
    var pages=[];
    for (var i=0;i<request.pages.length;i++) {
      var svg=request.pages[i], size=request.page_sizes ? request.page_sizes[i] : request.page;
      await yieldWriter();checkWriter(job);
      pages.push(await svgToPngBase64(svg,size.width,size.height,request.png_resolution,job.controller.signal,i+1));
    }
    return pages;
  };

  async function writeExhibit(request) {
    if (activeWriter) {activeWriter.cancelled = true;activeWriter.controller.abort();}
    var job = {id:request.job,cancelled:false,controller:new AbortController()}; activeWriter=job;
    var start=now();
    try {
      if (!Array.isArray(request.pages) || request.pages.length!==request.n_pages) throw Error('Invalid captured page count');
      var producer=exhibitProducers[request.format];
      if (!producer) throw Error('Unknown browser writer format');
      var pages=await producer(request,job);
      checkWriter(job);
      reply({job:request.job,source_job:request.source_job,format:request.format,n_pages:request.n_pages,
        pages:pages,timing:{encode_ms:Math.round(now()-start)},versions:versions()});
    } catch (error) {
      if (!job.cancelled) reply({job:request.job,source_job:request.source_job,format:request.format,
        error:String(error.message || error),code:error.vetsCode,page:error.vetsPage,resolution:error.vetsResolution});
    } finally {
      clearStage(); if (activeWriter===job) activeWriter=null;
    }
  }

  // The top bar's Figures buttons: ask R for a snapshot in this format.
  window.vetsExportFigures = function (format) {
    if (window.vetsEvent) window.vetsEvent('ws_export_figures', { format: format });
  };

  function bind() {
    if (window.__vetsExportBound) return;
    if (!window.Shiny || !Shiny.addCustomMessageHandler) return;
    window.__vetsExportBound = true;
    Shiny.addCustomMessageHandler('vets-write-exhibit', function (request) { writeExhibit(request); });
    Shiny.addCustomMessageHandler('vets-cancel-writer', function (message) {
      if (activeWriter && activeWriter.id === message.job) {
        activeWriter.cancelled = true;activeWriter.controller.abort();
      }
      if (latestJob === message.job) latestJob = null;
    });
    Shiny.addCustomMessageHandler('vets-export-started', function (message) { latestJob = message.job; });
    // R has staged the file: click the hidden download link so the browser
    // fetches it through the session's downloadHandler.
    Shiny.addCustomMessageHandler('vets-export-ready', function (m) {
      window.__vetsExportReady = m;
      var attempts = 0;
      function download() {
        if (latestJob !== m.job) return;
        var a = document.getElementById(m.download_id);
        if (a && a.getAttribute('href')) {
          // Copy PNG (#517): a clipboard job's bytes settle the copy request
          // m.clipboard names (vets.js, #610); only a file that names none downloads.
          if (m.clipboard && window.vetsCopyStaged && window.vetsCopyStaged(m, a.href)) return;
          a.click(); return;
        }
        if (++attempts < 100) setTimeout(download, 50);
        else {
          vetsEvent('vets_export_download_error', {job:m.job});
        }
      }
      download();
    });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bind);
  else bind();
})();
